### ISSUE TITLE
Tryby pracy pamięci

### ISSUE THREAD

**Issue by Wannabex** [Wannabex/sram_test_stand#2]
Fajnie by było jakby się dało z GUI przełączać pamięć między 3 trybami:
1. Standby
2. Output Disable
3. Operational - czyli można read i write robić
![srammody](https://user-images.githubusercontent.com/46918913/82759981-f10b8f80-9df0-11ea-8802-8898c498d984.PNG)
Do obsługi tego proponuję komendy typu "State -s standby/disable/operational /r/n"

Dodatkowo cieszyłbym się jakby się dało prostą komendą Power on/off dało sterować zasilanie całego Srama, ale jak SRAM jest prosto do VCC podłączony to już trudno

**Comment by mati97** [comment]
jest na sztywno do vcc. Proponuje state -s/-d/-o \r\n i komendy :
write 0x1ffff 0xff 0x69 0xcy 0xce ... \r\n, gdzie pierwsze to adres, drugie to liczba bajtów do zapisania, trzecie to już dane
read 0x000ff 0xbb \r\n gdzie pierwsze to adres, drugie to ile czytać
Adres zawsze 0x + 5 znaków, zeby mi sie łatwiej parsowało

**Comment by Wannabex** [comment]
Dobra super, to już wszystko jasne, wprowadzam to do gui!

**Comment by Wannabex** [comment]
A jeszcze jedno bo nie jestem pewien czy dobrze zrozumiałem.
Czy adres jako 0x + 5 znaków w stylu 0x000ff to masz na myśli wysyłanie 20 bitów?
Bo to i tak dobije do 24 bitów np - 0x00 0x00 0xff jako 3 kolejne bajty adresu.
0x01 0xff 0xff to największy możliwy adres, więc w teorii wystarczyłoby nawet 17 bitów, ale Uart nie pozwoli.

**Comment by Wannabex** [comment]
Już wiem
